### ISSUE TITLE
Are there guidelines for interpreting the results?

### ISSUE THREAD

**Issue by scharch** [airr-community/ogrdbstats#2]
I know this is asking a lot, but it would be great to have access to whatever rules of thumb you (and other IARC members) have developed from looking at hundreds of these things....

**Comment by williamdlees** [comment]
The key guidance is in [Ohlin et al.](https://www.frontiersin.org/articles/10.3389/fimmu.2019.00435/full). We have talked about publishing an update and will probably do that over the next year. In the meantime, we publish detailed reports on each sequence that's approved - as in [this example](https://ogrdb.airr-community.org/sequence/72).

**Comment by scharch** [comment]
Thanks. Have you worked with inferences from IgG at all? Unmutated frequencies are very low, so would you just put more emphasis on CDR3/J diversity and allele ratio?

**Comment by williamdlees** [comment]
The repertoires we work with are not highly mutated, and we tend not to look at more marginal cases. Have you searched VDJbase to see if we’ve found the same inferred allele in any repertoire? There is a search facility in the reports section.
 
J-gene haplotyping can be very powerful, if it’s available. A clear sign of the novel allele on one chromosome is a good sign.

We like to check that the reads don’t just arise from a single expanded clone. The CDR3 length plot produced by ogrdbstats is useful for that.

Feel free to send an example if you would like some guidance.
