### ISSUE TITLE
Non-human inferences

### ISSUE THREAD

**Issue by scharch** [airr-community/ogrdbstats#3]
Apologies if this is out-of-scope, but I can't find any other place to ask IARC questions...

Is there any thought on how to define genes vs alleles when running an inference on, say, monkeys? How do I tell if I am coming up with 3 alleles of the same gene (possible red flag) or 3 separate genes. Or if I end up with 75 alleles (reasonable, I think) from 66 genes (probably too many)?

**Comment by williamdlees** [comment]
This is best asked of the  GLDB macaque sub-group – but, as in the draft germline paper that is circulating at the moment, we think it is too early right now and will become a lot easier when more genomic evidence is available – but do raise it on the next macaque call 😊

 

From: Chaim Schramm ***@***.***> 
Sent: 22 May 2022 15:10
To: airr-community/ogrdbstats ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [airr-community/ogrdbstats] Non-human inferences (Issue #3)

 

Apologies if this is out-of-scope, but I can't find any other place to ask IARC questions...

Is there any thought on how to define genes vs alleles when running an inference on, say, monkeys? How do I tell if I am coming up with 3 alleles of the same gene (possible red flag) or 3 separate genes. Or if I end up with 75 alleles (reasonable, I think) from 66 genes (probably too many)?
